[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/small.json"
energy_trace = "energy-data/traces/clean_energy_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/small.json"
energy_trace = "energy-data/traces/clean_energy_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/small.json"
energy_trace = "energy-data/traces/fossil_heavy_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/small.json"
energy_trace = "energy-data/traces/fossil_heavy_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/small.json"
energy_trace = "energy-data/traces/mixed_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/small.json"
energy_trace = "energy-data/traces/mixed_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/large.json"
energy_trace = "energy-data/traces/clean_energy_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/large.json"
energy_trace = "energy-data/traces/clean_energy_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/large.json"
energy_trace = "energy-data/traces/fossil_heavy_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/large.json"
energy_trace = "energy-data/traces/fossil_heavy_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/large.json"
energy_trace = "energy-data/traces/mixed_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/large.json"
energy_trace = "energy-data/traces/mixed_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/mixed.json"
energy_trace = "energy-data/traces/clean_energy_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/mixed.json"
energy_trace = "energy-data/traces/clean_energy_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/mixed.json"
energy_trace = "energy-data/traces/fossil_heavy_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/mixed.json"
energy_trace = "energy-data/traces/fossil_heavy_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/mixed.json"
energy_trace = "energy-data/traces/mixed_trace.csv"
algorithm = "easy_bf"
queue_order = "fcfs"

[[experiments]]
platform = "platform/mustang_platform.xml"
workload = "workloads/mixed.json"
energy_trace = "energy-data/traces/mixed_trace.csv"
algorithm = "greenfilling"
queue_order = "fcfs"
variant_options = {tau = 0.1}
